Fix regular expression compatibility issue with node v12 (#604)
Summary:
**Summary**
This pull request fixes https://github.com/facebook/metro/issues/578 we have in regular expression treatment for converting OS specific path separators. When running in node js version 12, forward slashes in brackets (eg. `/[/\\]foo/` won't be escaped automatically (Also see another issue I filed in nodejs project https://github.com/nodejs/help/issues/3039). That is causing backward compatibility issue in our use case, where we assume they will always be escaped and replaced the string accordingly.

**Test plan**
Added new tests to cover this edge case. Those new tests should pass in both nodejs 10 and nodejs 12.

Before:
```
xch at xch-mbp in ~/oss/metro/packages/metro-configfix_regexp_metro_config
$ nvm use 10
Now using node v10.19.0 (npm v6.13.4)

xch at xch-mbp in ~/oss/metro/packages/metro-configfix_regexp_metro_config [!]
$ jest src/defaults/
jest-haste-map: Watchman crawl failed. Retrying once with node crawler.
  Usually this happens when watchman isn't running. Create an empty `.watchmanconfig` file in your project's root folder or initialize a git or hg repository in your project.
  Error: Watchman error: N8watchman22CommandValidationErrorE: failed to validate command: resolve_projpath:  None of the files listed in global config root_files are present in path `/Users/xch/oss/metro/packages/metro-config` or any of its parent directories.  root_files is defined by the `/etc/watchman.json` config file and includes `.watchmanconfig`.  One or more of these files must be present in order to allow a watch. Try pulling and checking out a newer version of the project?. Make sure watchman is running for this project. See https://facebook.github.io/watchman/docs/troubleshooting.
jest-haste-map: duplicate manual mock found: cosmiconfig
  The following files share their name; please delete one of them:
    * <rootDir>/build/__mocks__/cosmiconfig.js
    * <rootDir>/src/__mocks__/cosmiconfig.js

 PASS  src/defaults/__tests__/exclusionList-test.js
  exclusionList
    ✓ proves we can write to path.sep for setting up the tests (2 ms)
    ✓ converts forward slashes in the RegExp to the OS specific path separator in macOS/linux (2 ms)
    ✓ converts forward slashes in the RegExp to the OS specific path separator in windows
    ✓ converts forward slashes in the string to the OS specific path separator in macOS/linux (1 ms)
    ✓ converts forward slashes in the string to the OS specific path separator in windows
    ✓ converts forward slashes in the RegExp to the OS specific path separator for macOS/linux in nodejs 10 or below (1 ms)
    ✓ converts forward slashes in the RegExp to the OS specific path separator for windows in nodejs 10 or below

Test Suites: 1 passed, 1 total
Tests:       7 passed, 7 total
Snapshots:   0 total
Time:        0.824 s, estimated 1 s
Ran all test suites matching /src\/defaults\//i.

xch at xch-mbp in ~/oss/metro/packages/metro-configfix_regexp_metro_config [!]
$ nvm use 12
Now using node v12.18.4 (npm v6.14.6)

xch at xch-mbp in ~/oss/metro/packages/metro-configfix_regexp_metro_config [!]
$ jest src/defaults/
jest-haste-map: Watchman crawl failed. Retrying once with node crawler.
  Usually this happens when watchman isn't running. Create an empty `.watchmanconfig` file in your project's root folder or initialize a git or hg repository in your project.
  Error: Watchman error: N8watchman22CommandValidationErrorE: failed to validate command: resolve_projpath:  None of the files listed in global config root_files are present in path `/Users/xch/oss/metro/packages/metro-config` or any of its parent directories.  root_files is defined by the `/etc/watchman.json` config file and includes `.watchmanconfig`.  One or more of these files must be present in order to allow a watch. Try pulling and checking out a newer version of the project?. Make sure watchman is running for this project. See https://facebook.github.io/watchman/docs/troubleshooting.
jest-haste-map: duplicate manual mock found: cosmiconfig
  The following files share their name; please delete one of them:
    * <rootDir>/build/__mocks__/cosmiconfig.js
    * <rootDir>/src/__mocks__/cosmiconfig.js

 FAIL  src/defaults/__tests__/exclusionList-test.js
  exclusionList
    ✓ proves we can write to path.sep for setting up the tests (2 ms)
    ✓ converts forward slashes in the RegExp to the OS specific path separator in macOS/linux
    ✕ converts forward slashes in the RegExp to the OS specific path separator in windows (3 ms)
    ✓ converts forward slashes in the string to the OS specific path separator in macOS/linux (1 ms)
    ✓ converts forward slashes in the string to the OS specific path separator in windows
    ✓ converts forward slashes in the RegExp to the OS specific path separator for macOS/linux in nodejs 10 or below (1 ms)
    ✓ converts forward slashes in the RegExp to the OS specific path separator for windows in nodejs 10 or below

  ● exclusionList › converts forward slashes in the RegExp to the OS specific path separator in windows

    SyntaxError: Invalid regular expression: /(.*[\\\]foo[\\\]bar|website\\node_modules\\.*|.*\\__tests__\\.*)$/: Unterminated character class
        at new RegExp (<anonymous>)

      31 |
      32 | function exclusionList(additionalExclusions) {
    > 33 |   return new RegExp(
         |          ^
      34 |     '(' +
      35 |       (additionalExclusions || [])
      36 |         .concat(list)

      at exclusionList (src/defaults/exclusionList.js:33:10)
      at Object.<anonymous> (src/defaults/__tests__/exclusionList-test.js:59:34)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 6 passed, 7 total
Snapshots:   0 total
Time:        0.757 s, estimated 1 s
Ran all test suites matching /src\/defaults\//i.
```

After:
```
xch at xch-mbp in ~/oss/metro/packages/metro-configfix_regexp_metro_config
$ nvm use 10
Now using node v10.19.0 (npm v6.13.4)

xch at xch-mbp in ~/oss/metro/packages/metro-configfix_regexp_metro_config
$ jest src/defaults/
jest-haste-map: Watchman crawl failed. Retrying once with node crawler.
  Usually this happens when watchman isn't running. Create an empty `.watchmanconfig` file in your project's root folder or initialize a git or hg repository in your project.
  Error: Watchman error: N8watchman22CommandValidationErrorE: failed to validate command: resolve_projpath:  None of the files listed in global config root_files are present in path `/Users/xch/oss/metro/packages/metro-config` or any of its parent directories.  root_files is defined by the `/etc/watchman.json` config file and includes `.watchmanconfig`.  One or more of these files must be present in order to allow a watch. Try pulling and checking out a newer version of the project?. Make sure watchman is running for this project. See https://facebook.github.io/watchman/docs/troubleshooting.
jest-haste-map: duplicate manual mock found: cosmiconfig
  The following files share their name; please delete one of them:
    * <rootDir>/build/__mocks__/cosmiconfig.js
    * <rootDir>/src/__mocks__/cosmiconfig.js

 PASS  src/defaults/__tests__/exclusionList-test.js
  exclusionList
    ✓ proves we can write to path.sep for setting up the tests (2 ms)
    ✓ converts forward slashes in the RegExp to the OS specific path separator in macOS/linux (2 ms)
    ✓ converts forward slashes in the RegExp to the OS specific path separator in windows
    ✓ converts forward slashes in the string to the OS specific path separator in macOS/linux (1 ms)
    ✓ converts forward slashes in the string to the OS specific path separator in windows
    ✓ converts forward slashes in the RegExp to the OS specific path separator for macOS/linux in nodejs 10 or below
    ✓ converts forward slashes in the RegExp to the OS specific path separator for windows in nodejs 10 or below (1 ms)

Test Suites: 1 passed, 1 total
Tests:       7 passed, 7 total
Snapshots:   0 total
Time:        0.998 s, estimated 1 s
Ran all test suites matching /src\/defaults\//i.

xch at xch-mbp in ~/oss/metro/packages/metro-configfix_regexp_metro_config
$ nvm use 12
Now using node v12.18.4 (npm v6.14.6)

xch at xch-mbp in ~/oss/metro/packages/metro-configfix_regexp_metro_config
$ jest src/defaults/
jest-haste-map: Watchman crawl failed. Retrying once with node crawler.
  Usually this happens when watchman isn't running. Create an empty `.watchmanconfig` file in your project's root folder or initialize a git or hg repository in your project.
  Error: Watchman error: N8watchman22CommandValidationErrorE: failed to validate command: resolve_projpath:  None of the files listed in global config root_files are present in path `/Users/xch/oss/metro/packages/metro-config` or any of its parent directories.  root_files is defined by the `/etc/watchman.json` config file and includes `.watchmanconfig`.  One or more of these files must be present in order to allow a watch. Try pulling and checking out a newer version of the project?. Make sure watchman is running for this project. See https://facebook.github.io/watchman/docs/troubleshooting.
jest-haste-map: duplicate manual mock found: cosmiconfig
  The following files share their name; please delete one of them:
    * <rootDir>/build/__mocks__/cosmiconfig.js
    * <rootDir>/src/__mocks__/cosmiconfig.js

 PASS  src/defaults/__tests__/exclusionList-test.js
  exclusionList
    ✓ proves we can write to path.sep for setting up the tests (2 ms)
    ✓ converts forward slashes in the RegExp to the OS specific path separator in macOS/linux (1 ms)
    ✓ converts forward slashes in the RegExp to the OS specific path separator in windows
    ✓ converts forward slashes in the string to the OS specific path separator in macOS/linux (1 ms)
    ✓ converts forward slashes in the string to the OS specific path separator in windows
    ✓ converts forward slashes in the RegExp to the OS specific path separator for macOS/linux in nodejs 10 or below
    ✓ converts forward slashes in the RegExp to the OS specific path separator for windows in nodejs 10 or below (1 ms)

Test Suites: 1 passed, 1 total
Tests:       7 passed, 7 total
Snapshots:   0 total
Time:        0.741 s, estimated 1 s
Ran all test suites matching /src\/defaults\//i.
```

Pull Request resolved: https://github.com/facebook/metro/pull/604

Reviewed By: cpojer

Differential Revision: D24685554

Pulled By: MichaReiser

fbshipit-source-id: bcda6308db67d75c2c16ca2eb2fd7e0a59ef0b67