fix potential "invalid content type" error on /symbolicate #1629 (#1630)
Summary:
**It's my first PR, I have completed the CLA**

Fix: https://github.com/facebook/metro/issues/1629

In my case with RN0.80, /symbolicate receives request with `req.headers["content-type"]` containing `text/plain` instead of `application/json` but the content is indeed a JSON.
This causes this error message in the console :
```
Error: Invalid content type, expected application/json
    at .../node_modules/metro/src/lib/parseJsonBody.js:11:16
   ...
```
Calling jsonParseBody with `strict: false` disable the header validation and the request is processed correctly and I no longer get an error message.
So we can propably consider making this header check more flexible and reintroduce it later as a breaking change if necessary (the original change was not introduced as a breaking change)

Changelog: [Fix] potential "invalid content type" error on /symbolicate https://github.com/facebook/metro/issues/1629

Pull Request resolved: https://github.com/facebook/metro/pull/1630

Reviewed By: huntie, robhogan

Differential Revision: D89170225

Pulled By: vzaidman

fbshipit-source-id: 837cade6b8bba15c1a2611448ca362e41a251793