updated node-fetch (#1327)
Summary:
Pull Request resolved: https://github.com/facebook/metro/pull/1327

Updating `node-fetch` to the latest version caused tests in `packages/metro/src/integration_tests/__tests__/server-test.js` to fail. Running each test case inside the file failed individually, but there seems to have been a race condition between the tests causing subsequent tests to fail with the following error:
```
FetchError: request to http://localhost:10028/import-export/index.bundle?platform=ios&dev=true&minify=false failed, reason: socket hang up
```
It happens because the "connection: close" header is removed in the latest version of `node-fetch`: https://github.com/node-fetch/node-fetch/pull/1765 and can be fixed by adding this header manually to fetches.
```
fetch('path', {headers: {'Connection': 'close'}});
```
This diff introduces a workaround where we add that header, however `fetch` is expected to work even without it when the following bug is fixed: https://github.com/nodejs/node/issues/54484

Also, since `node-fetch` was only used in this one test, it was actually a good opportunity to remove it from the project's dependencies altogether.

Reviewed By: robhogan

Differential Revision: D61336391

fbshipit-source-id: 898c9745dbbc1e622699ff36b4112a95c3c68656